// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// insert_hinges
DataFrame insert_hinges(NumericVector x, NumericVector y, NumericVector hinges);
RcppExport SEXP photobiology_insert_hinges(SEXP xSEXP, SEXP ySEXP, SEXP hingesSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< NumericVector >::type hinges(hingesSEXP);
    __result = Rcpp::wrap(insert_hinges(x, y, hinges));
    return __result;
END_RCPP
}
// integrate_xy
double integrate_xy(NumericVector x, NumericVector y);
RcppExport SEXP photobiology_integrate_xy(SEXP xSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    __result = Rcpp::wrap(integrate_xy(x, y));
    return __result;
END_RCPP
}
// put_hinges
NumericVector put_hinges(NumericVector x, NumericVector y, NumericVector hinges);
RcppExport SEXP photobiology_put_hinges(SEXP xSEXP, SEXP ySEXP, SEXP hingesSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< NumericVector >::type hinges(hingesSEXP);
    __result = Rcpp::wrap(put_hinges(x, y, hinges));
    return __result;
END_RCPP
}
